# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wSelectFile.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_selectFile(object):
    def setupUi(self, selectFile):
        selectFile.setObjectName("selectFile")
        selectFile.setWindowModality(QtCore.Qt.ApplicationModal)
        selectFile.resize(308, 326)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        selectFile.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(selectFile)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbTRDI = QtWidgets.QCheckBox(selectFile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTRDI.sizePolicy().hasHeightForWidth())
        self.cbTRDI.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cbTRDI.setFont(font)
        self.cbTRDI.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbTRDI.setObjectName("cbTRDI")
        self.horizontalLayout.addWidget(self.cbTRDI)
        self.pbTRDI = QtWidgets.QPushButton(selectFile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbTRDI.sizePolicy().hasHeightForWidth())
        self.pbTRDI.setSizePolicy(sizePolicy)
        self.pbTRDI.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pbTRDI.setFont(font)
        self.pbTRDI.setAutoFillBackground(False)
        self.pbTRDI.setObjectName("pbTRDI")
        self.horizontalLayout.addWidget(self.pbTRDI)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pbQRev = QtWidgets.QPushButton(selectFile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbQRev.sizePolicy().hasHeightForWidth())
        self.pbQRev.setSizePolicy(sizePolicy)
        self.pbQRev.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pbQRev.setFont(font)
        self.pbQRev.setObjectName("pbQRev")
        self.horizontalLayout_3.addWidget(self.pbQRev)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pbCancel = QtWidgets.QPushButton(selectFile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCancel.sizePolicy().hasHeightForWidth())
        self.pbCancel.setSizePolicy(sizePolicy)
        self.pbCancel.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pbCancel.setFont(font)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout_4.addWidget(self.pbCancel)
        self.gridLayout.addLayout(self.horizontalLayout_4, 7, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pbSonTek = QtWidgets.QPushButton(selectFile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbSonTek.sizePolicy().hasHeightForWidth())
        self.pbSonTek.setSizePolicy(sizePolicy)
        self.pbSonTek.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pbSonTek.setFont(font)
        self.pbSonTek.setObjectName("pbSonTek")
        self.horizontalLayout_2.addWidget(self.pbSonTek)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.pbHelp = QtWidgets.QPushButton(selectFile)
        self.pbHelp.setMinimumSize(QtCore.QSize(40, 40))
        self.pbHelp.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pbHelp.setFont(font)
        self.pbHelp.setObjectName("pbHelp")
        self.gridLayout.addWidget(self.pbHelp, 1, 0, 1, 1, QtCore.Qt.AlignRight)

        self.retranslateUi(selectFile)
        QtCore.QMetaObject.connectSlotsByName(selectFile)
        selectFile.setTabOrder(self.pbSonTek, self.pbTRDI)
        selectFile.setTabOrder(self.pbTRDI, self.cbTRDI)
        selectFile.setTabOrder(self.cbTRDI, self.pbQRev)
        selectFile.setTabOrder(self.pbQRev, self.pbCancel)
        selectFile.setTabOrder(self.pbCancel, self.pbHelp)

    def retranslateUi(self, selectFile):
        _translate = QtCore.QCoreApplication.translate
        selectFile.setWindowTitle(_translate("selectFile", "Select File(s)"))
        self.cbTRDI.setText(_translate("selectFile", "Checked Only"))
        self.pbTRDI.setText(_translate("selectFile", "TRDI"))
        self.pbQRev.setText(_translate("selectFile", "QRev"))
        self.pbCancel.setText(_translate("selectFile", "Cancel"))
        self.pbSonTek.setText(_translate("selectFile", "SonTek"))
        self.pbHelp.setText(_translate("selectFile", "?"))

